

Q1. Student Performance DataFrame: Construction and Analysis
A college wants to analyze student performance using the following data.

data = {    "Student_ID": [        101, 102, 103, 104, 105, 106,        107, 108, 109, 110, 111, 112    ],    "Name": [        "Amit", "Priya", "Rahul", "Neha",        "Vikas", "Pooja", "Karan", "Simran",        "Arjun", "Meena", "Rohit", "Anjali"    ],    "Age": [        19, 20, 18, 21, 20, 19,        22, 18, 21, 20, 19, 22    ],    "Hours_Studied": [        2, 5, 3, 8, 6, 4,        9, 2, 7, 5, 6, 8    ],    "Attendance": [        65, 85, 70, 95, 88, 75,        98, 60, 90, 82, 86, 94    ],    "Marks": [        48, 78, 55, 92, 84, 67,        96, 45, 89, 76, 81, 93    ]}
Tasks:

Create a DataFrame and display its first five and last three records.
Determine the number of rows and columns programmatically. Verify that the result matches the expected dimensions.
Extract all column names as a Python list and classify them as identifiers, categorical attributes, or numerical attributes.
Select the Name, Hours_Studied, and Marks columns. Then identify students whose marks are above the dataset's average.
Reset the index after filtering, compare the original and new indices, and explain why an index should not automatically be treated as a student's unique identifier

In [1]:
import pandas as pd

In [2]:
data = {    "Student_ID": [ 
     101, 102, 103, 104, 105, 106,   107, 108, 109, 110, 111, 112    ],   
      "Name": [        "Amit", "Priya", "Rahul", "Neha",  "Vikas", "Pooja", "Karan", "Simran", "Arjun", "Meena", "Rohit", "Anjali"    ], 
      "Age": [        19, 20, 18, 21, 20, 19,        22, 18, 21, 20, 19, 22    ],
      "Hours_Studied": [        2, 5, 3, 8, 6, 4,        9, 2, 7, 5, 6, 8    ],    
      "Attendance": [        65, 85, 70, 95, 88, 75,        98, 60, 90, 82, 86, 94    ],  
        "Marks": [        48, 78, 55, 92, 84, 67,        96, 45, 89, 76, 81, 93    ]}

In [6]:
df=pd.DataFrame(data)

In [7]:
df

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [ ]:
df.head()  #for first 5 records

   Student_ID   Name  Age  Hours_Studied  Attendance  Marks
0         101   Amit   19              2          65     48
1         102  Priya   20              5          85     78
2         103  Rahul   18              3          70     55
3         104   Neha   21              8          95     92
4         105  Vikas   20              6          88     84

In [ ]:
df.tail(3)#for last 3 records

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [ ]:
df.shape #for table size

(12, 6)

In [ ]:
df.shape == (12, 6) # determine table size

True

In [25]:
print(type(df))

<class 'list'>

In [27]:
df

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [ ]:
import pandas as pd

df = pd.DataFrame(data)

print(type(df))#for colums name
print(df.columns.tolist())

<class 'pandas.DataFrame'>
['Student_ID', 'Name', 'Age', 'Hours_Studied', 'Attendance', 'Marks']

In [ ]:
#clasify all columns  name
Identifier = "Student_ID"
Categorical = "Name"
numerical= ["Age","Hours_Studied","Attendance","Marks"]
print('Identifier:',Identifier)
print('Categorical:',Categorical)
print('numerical:',numerical)

Identifier: Student_ID
Categorical: Name
numerical: ['Age', 'Hours_Studied', 'Attendance', 'Marks']

In [34]:
x=df[['Name','Hours_Studied','Marks']]
print(x)

      Name  Hours_Studied  Marks
0     Amit              2     48
1    Priya              5     78
2    Rahul              3     55
3     Neha              8     92
4    Vikas              6     84
5    Pooja              4     67
6    Karan              9     96
7   Simran              2     45
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

In [44]:
average= df['Marks'].mean()
result=df[df['Marks']>average]
print(result)
print('average =',average)

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
1          102   Priya   20              5          85     78
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
6          107   Karan   22              9          98     96
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93
average = 75.33333333333333

In [ ]:
#reset the index value
new_result = result.reset_index(drop=True)

print(result.index)
print(new_result.index)

Index([1, 3, 4, 6, 8, 9, 10, 11], dtype='int64')
RangeIndex(start=0, stop=8, step=1)